sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: Zq41itcUmy+BM0EEyrYxJfB3gfxoBvaoVXpdBlW37o60tAh8FfTWnzVzzzGnT7uHMmoj8KYUxn+HwmmE1LhMXG9fAZdN4YZXbqNJ6YBqaYqe0YPbaUa0rh3HPPR9dk4IwKucX3d1qBW5ds1OJzZmLEkqyH5In1FZqjAcLPZfUMBKm54tIqAt4KwbTDpMZs2RpVGYS3aYZ4b3QOlBlZucIdvWTGTJVQoV1iicLuCVzaHOBG8d76SG37q2Jc9CTk7Ff1l8daRLyYClvwGfwDEJvtNHDcVJJBES/GNt79xeD4Etxbhy+vTrJP5yodB++sef1wmyAaNYnrGIuVPCrzSn1ZlseyfQ8c0+obGSiFjEaVElAXvrTCpt+uuB/RBlVt6y37wiDH9xJRNG+scrqXtieSgFkAxoRoLXakErbzItcE2FtRC/r2Zz8Lodl5UvMmtSRvj8y1WwFujcAUVfB7t1t/MOYaHl6zSSgPDOdAk+tNDh1k/VH/ZaSjMeBJl9a2TF6h1ThWYWg2CzoewFXyn9CS/SRVNGZIWlTQ9HOGeHxXEDvtWtyMC3OEVvQmhcG3APGxk+TA3u0gxGdtV7PqkC9BZlYC//z1sSONbn+G8FYdrxSczXQ3yL1Lmx+b5PjS65Qw88ktqMWvDXwzZznCLKsFn/dp0g1BLLe7YzHmJh2eI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Arachne-Volume-05_5512
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy